version: '3.8'

services:
  # Servicio del Backend (FastAPI)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=sistema-notas-secret-key-change-in-production
      - DATABASE_URL=sqlite:///./data/sistema_notas.db
      - MAIL_USERNAME=${MAIL_USERNAME:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_FROM=${MAIL_FROM:-}
    volumes:
      - ./backend/data:/app/data
      - ./backend:/app
    restart: unless-stopped
    networks:
      - sistema-notas-network

  # Servicio del Frontend (React)
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - PORT=3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - sistema-notas-network

networks:
  sistema-notas-network:
    driver: bridge
