version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sistema_notas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Backend FastAPI
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=tu-clave-secreta-muy-segura-aqui-cambiar-en-produccion
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/sistema_notas
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    restart: unless-stopped

  # Frontend React
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
